"""Mutation-testing harness for the two accuracy gates: pipeline/validate/
(Gate A, ingest-time, staged-batch API) and pipeline/audit/ (Gate B, post-
build, data/+site-data/ API).

The premise: it is not enough that Gate A/Gate B's own unit tests pass --
this module proves the gates actually CATCH corruption, by taking one clean,
internally-consistent synthetic mini-repo (pipeline/tests/fixtures/mutation/
repo/, covering a monthly level+ytd retail-like series, a CPI-like index with
a rebase break, a ytd-only FAI-like series, a quarterly income-like series
with real_yoy, a 70-city panel, a derived ratio, a DG-sourced series with
archived raw responses, and an HTML-sourced series with an archived fixture
page) where BOTH gates pass clean, then applying one deliberate, named
corruption at a time and asserting:

  (a) the intended check catches it, at the expected severity;
  (b) the SAME construction with the corruption reverted -- built the exact
      same way, not just "the shared control elsewhere" -- still passes (so a
      check that simply always blocks would not silently satisfy this test);
  (c) no OTHER, unrelated check false-positives; a full scan of every other
      gate_a.*/gate_b.* check's status is asserted to be a documented subset
      (a check that fires for a genuinely-related reason -- e.g. an
      impossible-math yoy_base_tolerance BLOCK alongside a raw unit_magnitude
      BLOCK for the same 10,000x slip -- is recorded as an accepted side-catch,
      not hidden).

Fixture construction notes (see pipeline/tests/fixtures/mutation/repo/ itself
for the generated data): mut-retail-total's YoY history is pinned to EXACTLY
-0.6% for every 2025/2026 month by construction (every month's level is the
same calendar month one year prior, times exactly 0.994, both rounded to the
series' own display precision) -- this makes gate_a.seasonal_z's robust_z
history perfectly flat (MAD==0), so the sign_flip mutation's before/after
(z==0.0 vs z==+inf) is unambiguous rather than dependent on a hand-tuned
tolerance. site-data/ was generated by actually running `python -m
pipeline.build` against this fixture's data/ (mirrors pipeline/tests/
fixtures/audit/clean_repo's own convention -- see test_audit_helpers.py).

Isolation: this module owns pipeline/tests/test_mutation_gates.py and
pipeline/tests/fixtures/mutation/ only. It reuses pipeline/tests/
_validate_helpers.py's write_series/touch/make_batch/make_test_config/
make_test_calendar verbatim (only `make_context`'s hardcoded fixture-data-dir
plumbing is re-pointed at this module's own fixture, since that one helper
bakes in pipeline/tests/fixtures/validate/data specifically) and pipeline/
tests/test_audit_helpers.py's make_ctx verbatim (it is already generic over
repo_dir + labels). It talks to pipeline.validate/pipeline.audit's public
check functions directly -- never pipeline.runner -- to stay clear of
runner.py/field_map.yaml/build.py while those are under concurrent edit.
"""
from __future__ import annotations

import copy
import json
import random
from datetime import date
from pathlib import Path

import pytest

from pipeline.audit.checks import (
    CHECK_MODULES,
    archive_independent_sample,
    build_determinism,
    derived_recompute,
    dg_archive_sample,
    takeaway_numbers,
    yoy_break_nulls,
)
from pipeline.audit.models import AuditContext
from pipeline.normalize import NormalizeReport
from pipeline.tests._validate_helpers import (
    make_batch,
    make_test_calendar,
    make_test_config,
    touch,
    write_series,
)
from pipeline.tests.test_audit_helpers import make_ctx as _base_make_ctx
from pipeline.validate import gate
from pipeline.validate.batch import empty_batch
from pipeline.validate.checks import run_all
from pipeline.validate.checks.lifecycle import (
    check_archive_release_identity,
    check_break_no_yoy,
    check_calendar_expected,
    check_partial_parse_completeness,
    check_revision_flood,
)
from pipeline.validate.checks.statistics import (
    check_seasonal_z,
    check_ytd_arithmetic,
    check_yoy_base_tolerance,
)
from pipeline.validate.checks.structural import (
    check_catalog_consistency,
    check_period_monotonic,
    check_unit_magnitude,
)
from pipeline.validate.model import BLOCK, PASS, SKIP, WARN

# ---------------------------------------------------------------------------
# Fixture locations + shared constants
# ---------------------------------------------------------------------------

FIXTURE_REPO = Path(__file__).resolve().parent / "fixtures" / "mutation" / "repo"
FIXTURE_DATA = FIXTURE_REPO / "data"
FIXTURE_SERIES = FIXTURE_DATA / "series"
REAL_REPO_ROOT = Path(__file__).resolve().parent.parent.parent  # where the `pipeline` package resolves from

# After every series' own "latest" period (the latest is 2026-Q2/2026-07/
# 2026-06 depending on the series) but still inside every freshness budget --
# gate_b.freshness never blocks regardless, this just keeps its WARNs quiet.
TODAY = date(2026, 7, 20)

ALL_SERIES_IDS = [
    "mut-retail-total", "mut-retail-ex-auto", "mut-retail-online-goods", "mut-retail-online-share",
    "mut-cpi-break", "mut-fai", "mut-income-quarterly", "mut-tsf-flow", "mut-dg-level", "mut-70city-panel",
]

# Hand-curated labels for this fixture's own "mut-*" ids -- deliberately NOT
# the real pipeline/audit/labels.yaml, mirroring test_audit_helpers.py's own
# TEST_LABELS convention exactly (fully decoupled from the real catalog).
MUT_LABELS = {
    "mut-retail-total": {"label_zh": "测试_MUT_社会消费品零售总额", "unit": "亿元"},
    "mut-retail-ex-auto": {"label_zh": "测试_MUT_除汽车以外的消费品零售额", "unit": "亿元"},
    "mut-retail-online-goods": {"label_zh": "测试_MUT_网上商品零售额", "unit": "亿元"},
    "mut-retail-online-share": {"label_zh": "测试_MUT_网上商品零售额占比", "unit": "%", "no_source_text": True},
    "mut-cpi-break": {"label_zh": "测试_MUT_居民消费价格指数", "unit": "%"},
    "mut-fai": {"label_zh": "测试_MUT_固定资产投资完成额", "unit": "%"},
    "mut-income-quarterly": {"label_zh": "测试_MUT_居民人均可支配收入", "unit": "元"},
    "mut-tsf-flow": {"label_zh": "测试_MUT_社会融资规模增量", "unit": "亿元"},
    "mut-dg-level": {"label_zh": "测试_MUT_DG层级指标", "unit": "亿元"},
    "mut-70city-panel": {"label_zh": "测试_MUT_70 个大中城市房价", "unit": "%"},
}


# ---------------------------------------------------------------------------
# Gate A helpers -- mirrors pipeline/tests/_validate_helpers.py's own
# load_fixture_series/make_real_data_dir/make_context exactly, just pointed
# at THIS module's fixture data/ instead of pipeline/tests/fixtures/validate/
# data/ (that file's versions hardcode its own FIXTURES_DATA_DIR). Every
# other helper (write_series/touch/make_batch/make_test_config/
# make_test_calendar) is imported and reused verbatim above.
# ---------------------------------------------------------------------------


def load_fixture_series(series_id: str) -> dict:
    with (FIXTURE_SERIES / f"{series_id}.json").open("r", encoding="utf-8") as handle:
        return json.load(handle)


def make_real_data_dir(tmp_path: Path) -> Path:
    import shutil

    dest = tmp_path / "data"
    shutil.copytree(FIXTURE_DATA, dest)
    return dest


def make_context(
    tmp_path: Path,
    *,
    touched: list[str] | None = None,
    staged_overrides: dict[str, dict] | None = None,
    real_overrides: dict[str, dict] | None = None,
    batch=None,
    config=None,
    calendar=None,
    normalize_report=None,
    archive_source: str | None = None,
    today=None,
    missing_series: list[str] | None = None,
    archive_files: dict[str, list[str]] | None = None,
):
    import shutil

    real_data_dir = make_real_data_dir(tmp_path)
    staged_dir = tmp_path / "staged"
    staged_series_dir = staged_dir / "series"
    staged_series_dir.mkdir(parents=True, exist_ok=True)

    for series_id, data in (real_overrides or {}).items():
        write_series(real_data_dir / "series", series_id, data)

    for source, release_ids in (archive_files or {}).items():
        archive_source_dir = real_data_dir / "archive" / source
        archive_source_dir.mkdir(parents=True, exist_ok=True)
        for release_id in release_ids:
            (archive_source_dir / f"{release_id}.html").write_text("<html></html>", encoding="utf-8")

    staged_overrides = staged_overrides or {}
    touched = list(touched) if touched is not None else list(staged_overrides.keys())

    for series_id in touched:
        if series_id in staged_overrides:
            write_series(staged_series_dir, series_id, staged_overrides[series_id])
            continue
        src = real_data_dir / "series" / f"{series_id}.json"
        if src.exists():
            shutil.copy2(src, staged_series_dir / f"{series_id}.json")

    return gate.build_context(
        staged_dir,
        batch=batch if batch is not None else empty_batch(),
        real_data_dir=real_data_dir,
        config=config if config is not None else make_test_config(),
        calendar=calendar if calendar is not None else make_test_calendar(),
        touched_series=touched,
        missing_series=missing_series or [],
        normalize_report=normalize_report,
        archive_source=archive_source,
        today=today,
    )


def blocked_check_ids(ctx) -> set[str]:
    """Every gate_a.* check id whose overall status is BLOCK, from a full
    run_all(ctx) -- used to assert "no OTHER unrelated check blocks" as a
    precise subset check rather than eyeballing output."""
    return {r.check_id for r in run_all(ctx) if r.status == BLOCK}


def control_batch():
    """A Batch touching every non-panel series' own latest committed
    observation, unmodified -- "a fresh ingest run that changed nothing"."""
    items = []
    for series_id in ALL_SERIES_IDS:
        if series_id == "mut-70city-panel":
            continue
        data = load_fixture_series(series_id)
        last = data["observations"][-1]
        measures = {k: v for k, v in last.items() if k not in ("period", "span", "flags")}
        items.append(touch(series_id, last["period"], **measures))
    # source=None: no REQUIRED_ANCHORS table applies, so
    # gate_a.partial_parse_completeness skips cleanly rather than needing this
    # broad, multi-series batch to also carry a curated raw_source_fields set
    # (that anchor-completeness rule is exercised on its own dedicated Batch
    # in test_mut_partial_parse below).
    return make_batch(items, release_id="rel:control", source=None)


# ---------------------------------------------------------------------------
# Gate B helpers -- test_audit_helpers.make_ctx is already generic over
# repo_dir + labels, so it is reused verbatim; only the defaults (this
# fixture's own labels/as_of) are supplied here.
# ---------------------------------------------------------------------------


def make_ctx(repo_dir: Path, **kwargs):
    kwargs.setdefault("labels", MUT_LABELS)
    kwargs.setdefault("as_of", TODAY)
    return _base_make_ctx(repo_dir, **kwargs)


def copy_mutation_repo(tmp_path: Path) -> Path:
    import shutil

    dest = tmp_path / "repo"
    shutil.copytree(FIXTURE_REPO, dest)
    return dest


def gate_b_blocked_check_ids(ctx) -> set[str]:
    """Every gate_b.* check id (excluding build_determinism, which needs its
    own repo_root=REAL_REPO_ROOT context -- see test_control_gate_b_build_
    determinism_passes_clean) whose run against `ctx` has_block()."""
    out = set()
    for module in CHECK_MODULES:
        if module is build_determinism:
            continue
        if module.run(ctx).has_block():
            out.add(module.CHECK_ID)
    return out


def _build_determinism_ctx(data_dir: Path, site_data_dir: Path) -> AuditContext:
    return AuditContext(
        repo_root=REAL_REPO_ROOT,  # where the `pipeline` package actually resolves from
        data_dir=data_dir,
        site_data_dir=site_data_dir,
        catalog={},
        section_bundles={},
        panel_bundle_loader=lambda _pid: None,
        labels={},
        rng=random.Random(0),
        seed="mutation-gate-test",
        run_id="mutation-gate-test",
        offline=True,
        samples_per_section=5,
        as_of=TODAY,
        previous_diary=None,
    )


# ===========================================================================
# CONTROL -- both gates pass clean on the unmutated fixture.
# ===========================================================================


def test_control_gate_a_passes_clean(tmp_path):
    ctx = make_context(tmp_path, touched=ALL_SERIES_IDS, batch=control_batch(), today=TODAY)
    results = run_all(ctx)
    blocked = [r for r in results if r.status == BLOCK]
    assert not blocked, [(r.check_id, [f.message for f in r.findings]) for r in blocked]


def test_control_gate_b_passes_clean():
    ctx = make_ctx(FIXTURE_REPO, samples_per_section=25)
    for module in CHECK_MODULES:
        if module is build_determinism:
            continue
        report = module.run(ctx)
        assert not report.has_block(), (module.CHECK_ID, [f.to_dict() for f in report.findings if f.status == "block"])


def test_control_gate_b_build_determinism_passes_clean():
    ctx = _build_determinism_ctx(FIXTURE_REPO / "data", FIXTURE_REPO / "site-data")
    report = build_determinism.run(ctx)
    assert not report.has_block(), [f.to_dict() for f in report.findings if f.status == "block"]


# ===========================================================================
# 1. unit_slip -- a new observation x10,000 (亿<->万亿) -> gate_a.unit_magnitude BLOCK.
# ===========================================================================


def test_mut_unit_slip(tmp_path):
    real = load_fixture_series("mut-retail-total")
    real_history = copy.deepcopy(real)
    real_history["observations"] = real_history["observations"][:-1]  # "not on file yet"
    period = real["observations"][-1]["period"]

    def make(m_value):
        staged = copy.deepcopy(real)
        staged["observations"][-1]["m"] = m_value
        batch = make_batch([touch("mut-retail-total", period, m=m_value)])
        return make_context(
            tmp_path / f"case-{m_value}",
            real_overrides={"mut-retail-total": real_history},
            staged_overrides={"mut-retail-total": staged},
            batch=batch,
            today=TODAY,
            archive_files={"nbs-retail": ["rel:test"]},  # keep gate_a.archive_release_identity quiet; not this test's concern
        )

    clean_ctx = make(real["observations"][-1]["m"])
    assert check_unit_magnitude(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    mutated_ctx = make(real["observations"][-1]["m"] * 10000)
    assert check_unit_magnitude(mutated_ctx).status == BLOCK
    # Documented side-catch: a 10,000x slip on the level alone also makes the
    # UNCHANGED published m_yoy imply an impossible prior-year level via
    # gate_a.yoy_base_tolerance's own "off > 50%" branch -- a real, related
    # consequence of the same corruption, not a false positive.
    blocked = blocked_check_ids(mutated_ctx)
    assert "gate_a.unit_magnitude" in blocked
    assert blocked <= {"gate_a.unit_magnitude", "gate_a.yoy_base_tolerance"}


# ===========================================================================
# 2. sign_flip -- YoY -0.6 -> +0.6 -> gate_a.yoy_base_tolerance and/or
# gate_a.seasonal_z WARN+.
# ===========================================================================


def test_mut_sign_flip(tmp_path):
    real = load_fixture_series("mut-retail-total")
    real_history = copy.deepcopy(real)
    real_history["observations"] = real_history["observations"][:-1]
    period = real["observations"][-1]["period"]
    assert real["observations"][-1]["m_yoy"] == -0.6  # the exact value the task spec names

    def make(m_yoy, ytd_yoy):
        staged = copy.deepcopy(real)
        staged["observations"][-1]["m_yoy"] = m_yoy
        staged["observations"][-1]["ytd_yoy"] = ytd_yoy
        batch = make_batch([touch("mut-retail-total", period, m_yoy=m_yoy, ytd_yoy=ytd_yoy)])
        return make_context(
            tmp_path / f"case-{m_yoy}",
            real_overrides={"mut-retail-total": real_history},
            staged_overrides={"mut-retail-total": staged},
            batch=batch,
            today=TODAY,
            archive_files={"nbs-retail": ["rel:test"]},
        )

    clean_ctx = make(-0.6, -0.6)
    assert check_seasonal_z(clean_ctx).status == PASS  # z==0.0: matches a perfectly flat -0.6% history exactly
    assert check_yoy_base_tolerance(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    mutated_ctx = make(0.6, 0.6)
    # gate_a.yoy_base_tolerance does NOT catch this one empirically: the level
    # is untouched, so its |published - level-derived| gap is only ~1.2pp,
    # under the default 3.0pp tolerance. gate_a.seasonal_z DOES catch it: the
    # flat -0.6%-every-month history (see module docstring) gives a
    # median-absolute-deviation of exactly 0, so any departure from -0.6% is
    # an infinite z-score. This is the "and/or" the task spec allows for.
    assert check_yoy_base_tolerance(mutated_ctx).status == PASS
    seasonal = check_seasonal_z(mutated_ctx)
    assert seasonal.status == BLOCK
    assert any("inf" in f.message for f in seasonal.findings)
    assert blocked_check_ids(mutated_ctx) == {"gate_a.seasonal_z"}


def test_mut_sign_flip_gate_b_archive_gap(tmp_path):
    """GATE GAP: gate_b.archive_independent_sample does NOT catch this same
    sign flip against the archived HTML source, even though the task spec
    expects it to. Root cause, confirmed empirically (see pipeline/audit/
    kernel.py's _candidate_strings): a NEGATIVE candidate value gets
    additional 下降/负-prefixed search strings, but a POSITIVE candidate is
    just the bare magnitude ("0.6") -- so flipping the stored m_yoy/ytd_yoy
    from -0.6 to +0.6 still finds the substring "0.6" sitting right next to
    "下降0.6%" in the archived page and reports a false PASS instead of a
    mismatch. The fuzzy matcher verifies a NUMBER was printed near the label;
    it does not verify which directional verb (上涨/下降) it followed.
    xfail(strict=True): if this is ever fixed, this assertion starts passing
    and pytest will flag the newly-unnecessary xfail marker (XPASS) rather
    than silently keep hiding it.
    """
    repo_dir = copy_mutation_repo(tmp_path)
    path = repo_dir / "data" / "series" / "mut-retail-total.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    last = data["observations"][-1]
    assert last["m_yoy"] == -0.6
    last["m_yoy"] = 0.6
    last["ytd_yoy"] = 0.6
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

    report = archive_independent_sample.run(make_ctx(repo_dir, samples_per_section=25))
    hits = {f.field: f.status for f in report.findings if f.series == "mut-retail-total" and f.period == "2026-06"}
    assert hits, "mut-retail-total@2026-06 was not sampled at all"

    if all(status == "pass" for status in hits.values()):
        pytest.xfail(
            "GATE GAP: gate_b.archive_independent_sample cannot distinguish a "
            "YoY sign flip from the correct value when the archived page's "
            "magnitude text is unchanged -- kernel.py's positive-value "
            "candidate strings carry no directional (上涨/下降) prefix, only "
            "negative ones do. A sign-flipped published YoY silently PASSes."
        )
    assert any(status in ("block", "warn") for status in hits.values())


# ===========================================================================
# 3. period_shift -- new obs lands on the wrong month -> gate_a.calendar_expected BLOCK.
# ===========================================================================


def test_mut_period_shift(tmp_path):
    real = load_fixture_series("mut-retail-total")

    def make(period, m_value):
        staged = copy.deepcopy(real)
        staged["observations"].append({"period": period, "m": m_value, "src": "rel:test-shift"})
        batch = make_batch([touch("mut-retail-total", period, m=m_value)])
        return make_context(
            tmp_path / f"case-{period}",
            real_overrides={"mut-retail-total": real},
            staged_overrides={"mut-retail-total": staged},
            batch=batch,
            today=TODAY,
            archive_files={"nbs-retail": ["rel:test"]},
        )

    clean_ctx = make("2026-07", 4600.0)  # exactly one step past the real latest (2026-06)
    assert check_calendar_expected(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    mutated_ctx = make("2026-10", 4600.0)  # 4 steps past 2026-06 -- looks like the wrong release
    result = check_calendar_expected(mutated_ctx)
    assert result.status == BLOCK
    assert "2026-10" in result.findings[0].message
    assert blocked_check_ids(mutated_ctx) == {"gate_a.calendar_expected"}


# ===========================================================================
# 4. measure_swap -- m and ytd values exchanged -> gate_a.ytd_arithmetic
# (+unit_magnitude if magnitudes differ enough -- verified empirically not to
# here: m grows ~6x, well under the x100 unit_magnitude threshold).
# ===========================================================================


def test_mut_measure_swap(tmp_path):
    real = load_fixture_series("mut-retail-total")
    last = real["observations"][-1]
    prior = real["observations"][-2]

    def make(swap: bool):
        staged = copy.deepcopy(real)
        staged_last = staged["observations"][-1]
        if swap:
            staged_last["m"], staged_last["ytd"] = staged_last["ytd"], staged_last["m"]
        batch = make_batch([
            touch("mut-retail-total", staged_last["period"], m=staged_last["m"], ytd=staged_last["ytd"]),
            touch("mut-retail-total", prior["period"], m=prior["m"], ytd=prior["ytd"]),  # same batch -> BLOCK not WARN
        ])
        return make_context(
            tmp_path / f"case-{swap}",
            real_overrides={"mut-retail-total": real},
            staged_overrides={"mut-retail-total": staged},
            batch=batch,
            today=TODAY,
        )

    clean_ctx = make(False)
    assert check_ytd_arithmetic(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    mutated_ctx = make(True)
    result = check_ytd_arithmetic(mutated_ctx)
    assert result.status == BLOCK
    # after the swap, the "ytd" field on file holds what was originally "m"
    assert f"ytd({last['period']})={last['m']}" in result.findings[0].message
    # Documented side-catch: the same swap also makes the unchanged m_yoy/
    # ytd_yoy imply an impossible prior-year level in BOTH directions via
    # gate_a.yoy_base_tolerance -- a genuine consequence of the swap, not an
    # unrelated false positive. gate_a.unit_magnitude stays quiet: ytd(=
    # 4643.8's true magnitude, now living in "m") vs m(=27368.7, now living in
    # "ytd") is only a ~6x jump, well under the x100 unit-slip threshold.
    blocked = blocked_check_ids(mutated_ctx)
    assert "gate_a.ytd_arithmetic" in blocked
    assert blocked <= {"gate_a.ytd_arithmetic", "gate_a.yoy_base_tolerance"}
    assert check_unit_magnitude(mutated_ctx).status == PASS


# ===========================================================================
# 5. stock_flow_swap -- a 社融存量-style STOCK value written into the FLOW
# measure -> verified empirically: gate_a.unit_magnitude is the actual
# catcher (mut-tsf-flow has no "ytd" caliber at all, so ytd_arithmetic/
# yoy_base_tolerance simply have nothing to evaluate here -- confirmed via a
# full run_all scan, not assumed).
# ===========================================================================


def test_mut_stock_flow_swap(tmp_path):
    real = load_fixture_series("mut-tsf-flow")
    real_history = copy.deepcopy(real)
    real_history["observations"] = real_history["observations"][:-1]
    period = real["observations"][-1]["period"]

    def make(m_value):
        staged = copy.deepcopy(real)
        staged["observations"][-1]["m"] = m_value
        batch = make_batch([touch("mut-tsf-flow", period, m=m_value)])
        return make_context(
            tmp_path / f"case-{m_value}",
            real_overrides={"mut-tsf-flow": real_history},
            staged_overrides={"mut-tsf-flow": staged},
            batch=batch,
            today=TODAY,
            archive_files={"nbs-retail": ["rel:test"]},
        )

    clean_ctx = make(real["observations"][-1]["m"])  # 23200.0 -- a normal monthly flow print
    assert check_unit_magnitude(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    # A social-financing STOCK-scale figure (~407 万亿-equivalent, i.e.
    # roughly the real-world magnitude of 社会融资规模存量) mistakenly written
    # into the FLOW ("当月新增") measure.
    mutated_ctx = make(20_000_000.0)
    assert check_ytd_arithmetic(mutated_ctx).status == SKIP  # no "ytd" caliber on this series at all
    assert check_yoy_base_tolerance(mutated_ctx).status == SKIP  # no m_yoy either
    result = check_unit_magnitude(mutated_ctx)
    assert result.status == BLOCK
    assert "20000000" in result.findings[0].message.replace(".0", "")
    assert blocked_check_ids(mutated_ctx) == {"gate_a.unit_magnitude"}


# ===========================================================================
# 6. stale_reserve -- previous month's release re-served with an identical
# content hash claiming a new period -> gate_a.archive_release_identity BLOCK.
# ===========================================================================


def test_mut_stale_reserve(tmp_path):
    real = load_fixture_series("mut-retail-total")
    prev = real["observations"][-1]
    batch = make_batch(release_id="2026-07-16_stale-release", source="nbs-retail")

    def make(new_obs):
        staged = copy.deepcopy(real)
        staged["observations"].append(new_obs)
        report = NormalizeReport(new_observations=[("mut-retail-total", new_obs["period"])])
        return make_context(
            tmp_path / f"case-{new_obs['src']}",
            real_overrides={"mut-retail-total": real},
            staged_overrides={"mut-retail-total": staged},
            batch=batch,
            normalize_report=report,
            archive_files={"nbs-retail": ["2026-07-16_stale-release"]},
            today=TODAY,
        )

    clean_ctx = make({"period": "2026-07", "m": 4700.0, "ytd": round(prev["ytd"] + 4700.0, 1), "m_yoy": -0.6, "ytd_yoy": -0.6, "src": "rel:20260716-fresh"})
    assert check_archive_release_identity(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    # Every shared measure byte-identical to the immediately preceding period.
    stale_obs = {"period": "2026-07", "m": prev["m"], "ytd": prev["ytd"], "m_yoy": prev["m_yoy"], "ytd_yoy": prev["ytd_yoy"], "src": "rel:20260716-stale"}
    mutated_ctx = make(stale_obs)
    result = check_archive_release_identity(mutated_ctx)
    assert result.status == BLOCK
    assert "stale re-serve" in result.findings[0].message
    # Documented side-catches (both WARN, not BLOCK): repeating last month's
    # numbers verbatim as a "new" period also breaks the additive ytd(t) ==
    # ytd(t-1)+m(t) relationship (ytd didn't grow at all) and the level-vs-
    # published-yoy cross-check -- real, related symptoms of the same
    # corruption, at WARN severity.
    assert blocked_check_ids(mutated_ctx) == {"gate_a.archive_release_identity"}


# ===========================================================================
# 7. partial_parse -- a required anchor group missing from the parsed batch
# -> gate_a.partial_parse_completeness BLOCK.
# ===========================================================================


def test_mut_partial_parse(tmp_path):
    all_groups = {"社会消费品零售总额", "城镇", "乡村", "商品零售额", "餐饮收入", "网上商品零售额"}
    missing_online = all_groups - {"网上商品零售额"}

    clean_ctx = make_context(tmp_path / "clean", touched=[], batch=make_batch(source="nbs-retail", raw_source_fields=all_groups), today=TODAY)
    assert check_partial_parse_completeness(clean_ctx).status == PASS

    mutated_ctx = make_context(tmp_path / "mutated", touched=[], batch=make_batch(source="nbs-retail", raw_source_fields=missing_online), today=TODAY)
    result = check_partial_parse_completeness(mutated_ctx)
    assert result.status == BLOCK
    assert "'online'" in result.findings[0].message
    assert blocked_check_ids(mutated_ctx) == {"gate_a.partial_parse_completeness"}


# ===========================================================================
# 8. revision_flood -- 50 historical values "revised" in one staged batch ->
# gate_a.revision_flood BLOCK.
# ===========================================================================


def test_mut_revision_flood(tmp_path):
    real = load_fixture_series("mut-retail-total")

    def build(n_periods: int, delta: float = 0.1):
        staged = copy.deepcopy(real)
        revisions = []
        for obs in staged["observations"][:n_periods]:
            old_m, old_ytd = obs["m"], obs["ytd"]
            obs["m"] = round(old_m + delta, 4)
            obs["ytd"] = round(old_ytd + delta, 4)
            revisions.append({"period": obs["period"], "measure": "m", "old": old_m, "new": obs["m"], "revised_on": TODAY.isoformat(), "source": "rel:test-revision", "series_id": "mut-retail-total"})
            revisions.append({"period": obs["period"], "measure": "ytd", "old": old_ytd, "new": obs["ytd"], "revised_on": TODAY.isoformat(), "source": "rel:test-revision", "series_id": "mut-retail-total"})
        return staged, revisions

    staged_clean, revisions_clean = build(1)  # 2 revisions -- comfortably under max_per_release=6
    ctx_clean = make_context(tmp_path / "clean", staged_overrides={"mut-retail-total": staged_clean}, normalize_report=NormalizeReport(revisions=revisions_clean), today=TODAY)
    assert check_revision_flood(ctx_clean).status == PASS
    assert blocked_check_ids(ctx_clean) == set()

    staged_flood, revisions_flood = build(25)  # 50 revisions, matching the task spec's own number
    assert len(revisions_flood) == 50
    ctx_flood = make_context(tmp_path / "flood", staged_overrides={"mut-retail-total": staged_flood}, normalize_report=NormalizeReport(revisions=revisions_flood), today=TODAY)
    result = check_revision_flood(ctx_flood)
    assert result.status == BLOCK
    assert result.findings[0].needs_ack
    assert blocked_check_ids(ctx_flood) == {"gate_a.revision_flood"}


# ===========================================================================
# 9. jan_feb_mishandle -- a jan_feb-flagged observation anchored on the wrong
# period (span/anchor wrong) -> gate_a.period_monotonic BLOCK. (A bare,
# unflagged standalone January print does NOT trip this check at all --
# period_monotonic's jan_feb rule only fires when the "jan_feb" flag itself
# is present with the wrong period/span, per its own literal logic; that is
# the variant the task spec's own "(or span/anchor wrong)" clause covers.)
# ===========================================================================


def test_mut_jan_feb_mishandle(tmp_path):
    real = load_fixture_series("mut-retail-total")

    clean_ctx = make_context(tmp_path / "clean", staged_overrides={"mut-retail-total": copy.deepcopy(real)}, today=TODAY)
    assert check_period_monotonic(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    staged = copy.deepcopy(real)
    insert_at = next(i for i, o in enumerate(staged["observations"]) if o["period"] == "2026-02")
    staged["observations"].insert(insert_at, {"period": "2026-01", "span": 2, "flags": ["jan_feb"], "m": 9000.0, "src": "rel:fake-anchor"})
    mutated_ctx = make_context(tmp_path / "mutated", staged_overrides={"mut-retail-total": staged}, today=TODAY)
    result = check_period_monotonic(mutated_ctx)
    assert result.status == BLOCK
    assert "jan_feb flag requires period YYYY-02 and span:2" in result.findings[0].message
    assert blocked_check_ids(mutated_ctx) == {"gate_a.period_monotonic"}


# ===========================================================================
# 10. break_crossing_yoy -- a YoY value written inside a break's no-yoy
# window -> gate_a.break_no_yoy BLOCK.
# ===========================================================================


def test_mut_break_crossing_yoy(tmp_path):
    real = load_fixture_series("mut-cpi-break")

    clean_ctx = make_context(tmp_path / "clean", staged_overrides={"mut-cpi-break": copy.deepcopy(real)}, today=TODAY)
    assert check_break_no_yoy(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    staged = copy.deepcopy(real)
    obs = next(o for o in staged["observations"] if o["period"] == "2026-03")  # inside [2025-07, 2026-07)
    obs["m_yoy"] = 1.3
    mutated_ctx = make_context(tmp_path / "mutated", staged_overrides={"mut-cpi-break": staged}, today=TODAY)
    result = check_break_no_yoy(mutated_ctx)
    assert result.status == BLOCK
    assert "inside no_yoy window" in result.findings[0].message
    assert blocked_check_ids(mutated_ctx) == {"gate_a.break_no_yoy"}


# ===========================================================================
# 11. catalog_drift -- a staged series' value_type mismatches its catalog
# entry -> gate_a.catalog_consistency BLOCK.
# ===========================================================================


def test_mut_catalog_drift(tmp_path):
    real = load_fixture_series("mut-fai")

    clean_ctx = make_context(tmp_path / "clean", staged_overrides={"mut-fai": copy.deepcopy(real)}, today=TODAY)
    assert check_catalog_consistency(clean_ctx).status == PASS
    assert blocked_check_ids(clean_ctx) == set()

    staged = copy.deepcopy(real)
    staged["value_type"] = "level"  # catalog.json still declares "yoy_pct"
    mutated_ctx = make_context(tmp_path / "mutated", staged_overrides={"mut-fai": staged}, today=TODAY)
    result = check_catalog_consistency(mutated_ctx)
    assert result.status == BLOCK
    assert "value_type" in result.findings[0].message
    assert blocked_check_ids(mutated_ctx) == {"gate_a.catalog_consistency"}


# ===========================================================================
# 12. derived_perturbation -- a derived series value nudged so it no longer
# equals its recomputation -> gate_b.derived_recompute BLOCK.
# ===========================================================================


def test_mut_derived_perturbation(tmp_path):
    clean_ctx = make_ctx(FIXTURE_REPO)
    clean_report = derived_recompute.run(clean_ctx)
    assert not clean_report.has_block()

    repo_dir = copy_mutation_repo(tmp_path)
    path = repo_dir / "data" / "series" / "mut-retail-online-share.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    correct = data["observations"][-1]["m"]
    assert correct != 12.34
    data["observations"][-1]["m"] = 12.34  # not 100 * online-goods.m / ex-auto.m
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

    mutated_ctx = make_ctx(repo_dir)
    report = derived_recompute.run(mutated_ctx)
    assert report.has_block()
    hit = [f for f in report.findings if f.status == "block" and f.series == "mut-retail-online-share"]
    assert hit and hit[0].rule == "ratio" and hit[0].observed == 12.34
    assert gate_b_blocked_check_ids(mutated_ctx) == {"gate_b.derived_recompute"}


# ===========================================================================
# 13. takeaway_drift -- bundle takeaway string number != stored measure ->
# gate_b.takeaway_numbers BLOCK.
# ===========================================================================


def test_mut_takeaway_drift():
    clean_ctx = make_ctx(FIXTURE_REPO)
    assert not takeaway_numbers.run(clean_ctx).has_block()

    mutated_ctx = make_ctx(FIXTURE_REPO)
    mutated_ctx.section_bundles = copy.deepcopy(mutated_ctx.section_bundles)
    entry = next(e for e in mutated_ctx.section_bundles["consumption"]["series"] if e["id"] == "mut-retail-total")
    assert "0.6%" in entry["takeaway"]
    entry["takeaway"] = entry["takeaway"].replace("0.6%", "9.9%")

    report = takeaway_numbers.run(mutated_ctx)
    assert report.has_block()
    hit = [f for f in report.findings if f.status == "block" and f.series == "mut-retail-total"]
    assert hit and hit[0].observed == 9.9
    assert gate_b_blocked_check_ids(mutated_ctx) == {"gate_b.takeaway_numbers"}


# ===========================================================================
# 14. bundle_break_leak -- yoy array carries a value across a break in the
# bundle -> gate_b.yoy_break_nulls BLOCK.
# ===========================================================================


def test_mut_bundle_break_leak():
    clean_ctx = make_ctx(FIXTURE_REPO)
    assert not yoy_break_nulls.run(clean_ctx).has_block()

    mutated_ctx = make_ctx(FIXTURE_REPO)
    mutated_ctx.section_bundles = copy.deepcopy(mutated_ctx.section_bundles)
    entry = next(e for e in mutated_ctx.section_bundles["prices"]["series"] if e["id"] == "mut-cpi-break")
    point = next(p for p in entry["yoy_series"] if p["period"] == "2026-03")  # inside [2025-07, 2026-07)
    assert point["yoy"] is None
    point["yoy"] = 1.3

    report = yoy_break_nulls.run(mutated_ctx)
    assert report.has_block()
    hit = [f for f in report.findings if f.status == "block" and f.series == "mut-cpi-break"]
    assert hit and hit[0].field == "yoy_series.yoy" and hit[0].period == "2026-03"
    assert gate_b_blocked_check_ids(mutated_ctx) == {"gate_b.yoy_break_nulls"}


# ===========================================================================
# 15. nondeterminism -- a rebuild differs from the deployed site-data ->
# gate_b.build_determinism BLOCK (via injecting a timestamp-ish difference
# into the site-data COPY -- data/ itself is never touched, so the check's
# own internal `python -m pipeline.build` rebuild stays byte-identical to
# what generated the committed fixture, and only the copy under test drifts).
# ===========================================================================


def test_mut_nondeterminism(tmp_path):
    clean_ctx = _build_determinism_ctx(FIXTURE_REPO / "data", FIXTURE_REPO / "site-data")
    assert not build_determinism.run(clean_ctx).has_block()

    repo_dir = copy_mutation_repo(tmp_path)
    index_path = repo_dir / "site-data" / "index.json"
    index = json.loads(index_path.read_text(encoding="utf-8"))
    original_generated_at = index["generated_at"]
    index["generated_at"] = "2099-01-01T00:00:00Z"  # a timestamp-ish difference; data/ is untouched
    assert index["generated_at"] != original_generated_at
    index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    mutated_ctx = _build_determinism_ctx(repo_dir / "data", repo_dir / "site-data")
    report = build_determinism.run(mutated_ctx)
    assert report.has_block()
    hit = [f for f in report.findings if f.status == "block" and f.field == "index.json"]
    assert hit


# ===========================================================================
# 16. archive_mismatch -- archived DG payload value differs from the stored
# series value -> gate_b.dg_archive_sample BLOCK.
# ===========================================================================


def test_mut_archive_mismatch(tmp_path):
    clean_ctx = make_ctx(FIXTURE_REPO, samples_per_section=10)
    assert not dg_archive_sample.run(clean_ctx).has_block()

    repo_dir = copy_mutation_repo(tmp_path)
    path = repo_dir / "data" / "series" / "mut-dg-level.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    for obs in data["observations"]:
        if obs["period"] == "2026-06":
            obs["m"] = -42.0  # archived DG value ("v") for this period is 1250.0
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

    mutated_ctx = make_ctx(repo_dir, samples_per_section=10)
    report = dg_archive_sample.run(mutated_ctx)
    assert report.has_block()
    hit = [f for f in report.findings if f.status == "block" and f.series == "mut-dg-level" and f.period == "2026-06"]
    assert hit
    # Documented side-catch: gate_b.archive_independent_sample independently
    # samples every series' latest observation too (stratum a), and shares
    # dg_archive.verify_observation's exact matching logic -- both checks
    # legitimately flag the SAME real mismatch via two different sampling
    # strategies; this is defense-in-depth, not an unrelated false positive.
    blocked = gate_b_blocked_check_ids(mutated_ctx)
    assert "gate_b.dg_archive_sample" in blocked
    assert blocked <= {"gate_b.dg_archive_sample", "gate_b.archive_independent_sample"}
