"""Shared test-only helpers for pipeline/tests/test_audit_*.py. Matches the
test_audit_*.py glob so it lives in this package's owned path set, but defines
no `test_*` functions itself -- pytest collects it (0 tests found) without
error, and every other test_audit_*.py file imports from it directly.

`FIXTURES_DIR` is the "clean_repo" synthetic fixture tree (data/ + site-data/
+ archive/): a small, internally-consistent catalog covering a break, a
Jan-Feb print, revisions, all four derived rules (single_from_ytd, ratio,
simple_mean_of_cities, count_cities_gt_zero), a 3-city panel, and two
DG-sourced series (one plain agency, one association-agency). Its
site-data/ was generated by actually RUNNING `python -m pipeline.build`
against its data/ (a one-off generation step, not something pipeline/audit
does at runtime) rather than hand-authored, so bundle content (yoy_series,
headline, takeaway, streak, ...) is byte-correct by construction instead of
hand-reproducing build.py's own logic in a test fixture.
"""
from __future__ import annotations

import random
import shutil
from datetime import date
from pathlib import Path

from pipeline.audit.models import AuditContext
from pipeline.audit.site_data import load_all_section_bundles, load_catalog, make_panel_bundle_loader

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures" / "audit"
CLEAN_REPO = FIXTURES_DIR / "clean_repo"

# Hand-curated labels for the synthetic catalog's own series ids -- deliberately
# NOT the real pipeline/audit/labels.yaml (whose ids are all real nbs-*/pbc-*/
# mof-*/cflp-* series), so these tests are fully decoupled from that file.
TEST_LABELS = {
    "test-cpi-break": {"label_zh": "测试_居民消费价格指数", "unit": "%"},
    "test-retail-total": {"label_zh": "测试_社会消费品零售总额", "unit": "亿元"},
    "test-retail-ex-auto": {"label_zh": "测试_除汽车以外的消费品零售额", "unit": "亿元"},
    "test-retail-online-goods": {"label_zh": "测试_网上商品零售额", "unit": "亿元", "no_source_text": True},
    "test-retail-online-share": {"label_zh": "测试_网上商品零售额占比", "unit": "%", "no_source_text": True},
    "test-tax-a": {"label_zh": "测试_契税收入", "unit": "亿元"},
    "test-tax-b": {"label_zh": "测试_土地增值税收入", "unit": "亿元"},
    "test-tax-total": {"label_zh": "测试_地产相关税收合计", "unit": "亿元", "no_source_text": True},
    "test-70city-newhome-mom": {"label_zh": "测试_70城新房价格", "unit": "%", "no_source_text": True},
    "test-70city-newhome-up-count": {"label_zh": "测试_70城新房上涨城市数", "unit": "个", "no_source_text": True},
    "test-70city-panel": {"label_zh": "测试_70 个大中城市房价", "unit": "%"},
    "test-dg-level": {"label_zh": "测试_DG层级指标", "unit": "亿元"},
    "test-pmi": {"label_zh": "测试_采购经理指数", "unit": "%"},
}


def copy_clean_repo(tmp_path: Path) -> Path:
    """Copy clean_repo/ to tmp_path so a test can freely corrupt files without
    touching the committed fixture (mirrors pipeline/tests/test_build.py's own
    tmp_path + fixture-copy convention)."""
    dest = tmp_path / "repo"
    shutil.copytree(CLEAN_REPO, dest)
    return dest


def make_ctx(
    repo_dir: Path,
    *,
    labels: dict | None = None,
    seed: str = "test-seed",
    samples_per_section: int = 25,
    as_of: date = date(2026, 7, 8),
    previous_diary: dict | None = None,
    offline: bool = True,
) -> AuditContext:
    """Build a real AuditContext against a fixture tree shaped like
    repo_dir/data + repo_dir/site-data (i.e. what copy_clean_repo returns, or
    clean_repo itself for read-only tests)."""
    data_dir = repo_dir / "data"
    site_data_dir = repo_dir / "site-data"
    catalog = load_catalog(data_dir)
    section_bundles = load_all_section_bundles(site_data_dir, catalog)
    return AuditContext(
        repo_root=repo_dir,
        data_dir=data_dir,
        site_data_dir=site_data_dir,
        catalog=catalog,
        section_bundles=section_bundles,
        panel_bundle_loader=make_panel_bundle_loader(site_data_dir),
        labels=TEST_LABELS if labels is None else labels,
        rng=random.Random(seed),
        seed=seed,
        run_id=seed,
        offline=offline,
        samples_per_section=samples_per_section,
        as_of=as_of,
        previous_diary=previous_diary,
    )
